
################################################################################
# Monitoring Cluster
################################################################################
start_monitoring:
	vagrant --design=designs/Vagrant_monitoring.yaml up

destroy_monitoring:
	vagrant --design=designs/Vagrant_monitoring.yaml destroy

halt_monitoring:
	vagrant --design=designs/Vagrant_monitoring.yaml halt

reload_monitoring: 
	vagrant --design=designs/Vagrant_monitoring.yaml reload

status_monitoring:
	vagrant --design=designs/Vagrant_monitoring.yaml status

