require 'yaml'
require 'pp'

conf = YAML.load_file( "Puppetconf.yaml" )
Puppetconf = conf["puppet-master"]

Vagrant.configure("2") do |config|
	config.vm.define "puppet-master" do |puppet|
		puppet.vm.box = "centos/7"
		puppet.vm.hostname = Puppetconf["hostname"]
		puppet.vm.synced_folder '.', '/vagrant'

		$provisioning_args = "-i #{Puppetconf['ip']}"

		if Puppetconf.key?("gitcode_path")
		  #This file is mounted here because the final location is decided on the provisioning script depending on different circumstances.
			#This also prevents r10k overwritting whatever is being shared in the final location.
			puppet.vm.synced_folder Puppetconf["gitcode_path"], "/opt/puppet-code"
		end

		if Puppetconf.key?("shared_hiera") and Puppetconf["shared_hiera"]
			puppet.vm.synced_folder Puppetconf["shared_hiera_path"], "/etc/puppetlabs/code/hieradata/production"
			$provisioning_args = $provisioning_args + " -S"
		end

		if Puppetconf.key?("module_development")
			puppet.vm.synced_folder Puppetconf["module_development"]["module_code_orig_path"], "/opt/#{Puppetconf['module_development']['module_name']}"
			$provisioning_args = $provisioning_args + " -m #{Puppetconf['module_development']['module_name']} -M #{Puppetconf['module_development']['module_puppet_environment']}"
		end
		
		puppet.vm.provision :shell, :path => 'provision-script.sh', :args => $provisioning_args

		puppet.vm.network "private_network", ip: Puppetconf["ip"]
		puppet.ssh.forward_x11 = true
		puppet.vm.provider "virtualbox" do |v|
			v.name = Puppetconf["hostname"]
			v.memory = Puppetconf["memory"]
			v.cpus = Puppetconf["cpu"]
			v.customize ["modifyvm", :id, "--audio", "none"]
		end
	end
end
